# Generated by Django 2.2 on 2021-07-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blogger',
            field=models.BooleanField(default=False),
        ),
    ]
